# Generated by Django 2.2 on 2019-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirect',
            name='id',
        ),
        migrations.AlterField(
            model_name='redirect',
            name='from_url',
            field=models.CharField(db_index=True, help_text="Absolute path, excluding the domain. Example: '/about/'", max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='From URL'),
        ),
    ]
